kind: pipeline
type: docker
name: build bot api

platform:
  os: linux
  arch: amd64

steps:
  - name: submodules
    image: alpine/git
    commands:
    - git submodule update --init --recursive
    
  - name: build image
    image: thegeeklab/drone-docker-buildx
    privileged: true
    settings:
      dry_run: false
      tags: latest
      auto_tag: true
      username:
          from_secret: git_user
      password:
          from_secret: git_pass
      registry:
          from_secret: git_url
      repo: git.nbots.ga/images/tdlight-botapi