kind: pipeline
type: docker
name: build bot api

platform:
  os: linux
  arch: arm64


steps:
  - name: submodules
    image: alpine/git
    commands:
    - git submodule update --init --recursive

  - name: build image
    image: thegeeklab/drone-docker-buildx
    privileged: true
    settings:
      auto_tag: true
      username: 
        from_secret: git_user
      password: 
        from_secret: git_pass
      registry: 
        from_secret: git_url
      repo: 
        from_secret: images/tdlight-botapi
      build_args: '--push'
      # tags: latest
