kind: pipeline
type: docker
name: build bot api

platform:
  os: linux
  arch: arm64

steps:
  - name: build image
    image: thegeeklab/drone-docker-buildx
    privileged: true
    environment:
      URL:
        from_secret: git_url
    settings:
      username: 
        from_secret: git_user
      password: 
        from_secret: git_pass
      repo: $${URL}/images/tdlight-botapi
      tags: latest
