name: Docker multi-arch build and push - gitea

on:
  push:
  pull_request:


jobs:
  build:
    name: Build Docker image (${{ matrix.arch }})
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repo
        uses: actions/checkout@v4.1.4
        with:
          submodules: "recursive"

      - name: Login to ghcr registry
        uses: docker/login-action@v3.1.0
        if: ${{ github.event_name != 'pull_request' }}
        with:
          registry: ${{ vars.REGISTRY_URL }}
          username: ${{ gitea.repository_owner }}
          password: ${{ secrets.GITEA_TOKEN}}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ vars.REGISTRY_URL }}/${{ gitea.actor }}/tdlightbotapi

      - name: Build image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          # tags: |
          #   ${{ vars.REGISTRY_URL }}/tdlight-telegram-bot-api2:${{gitea.sha}}
          #   ${{ vars.REGISTRY_URL }}/tdlight-telegram-bot-api2:latest
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
